import type * as MonacoType from 'monaco-editor'
import type { ITheme } from '@xterm/xterm'

export const terminalFontFamily = "ui-monospace, 'SFMono-Regular', Menlo, Monaco, 'Cascadia Mono', 'DejaVu Sans Mono', 'Liberation Mono', Consolas, 'Courier New', monospace"

export const gruvboxTerminalTheme: ITheme = {
  background: '#1d2021',
  foreground: '#ebdbb2',
  cursor: '#fabd2f',
  selectionBackground: 'rgba(250, 189, 47, 0.22)',
  black: '#282828',
  red: '#cc241d',
  green: '#98971a',
  yellow: '#d79921',
  blue: '#458588',
  magenta: '#b16286',
  cyan: '#689d6a',
  white: '#a89984',
  brightBlack: '#928374',
  brightRed: '#fb4934',
  brightGreen: '#b8bb26',
  brightYellow: '#fabd2f',
  brightBlue: '#83a598',
  brightMagenta: '#d3869b',
  brightCyan: '#8ec07c',
  brightWhite: '#ebdbb2',
}

export const gruvboxMonacoTheme: MonacoType.editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '928374', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: 'a89984', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'fb4934' },
    { token: 'keyword.control', foreground: 'fb4934' },
    { token: 'keyword.operator', foreground: 'fe8019' },
    { token: 'storage', foreground: 'd3869b' },
    { token: 'storage.type', foreground: 'fabd2f' },
    { token: 'string', foreground: 'b8bb26' },
    { token: 'string.escape', foreground: '8ec07c', fontStyle: 'bold' },
    { token: 'string.template', foreground: 'b8bb26' },
    { token: 'number', foreground: 'd3869b' },
    { token: 'number.float', foreground: 'd3869b' },
    { token: 'number.hex', foreground: 'fe8019' },
    { token: 'type', foreground: 'fabd2f' },
    { token: 'type.identifier', foreground: 'fabd2f' },
    { token: 'class', foreground: 'fabd2f' },
    { token: 'class.name', foreground: 'fabd2f' },
    { token: 'interface', foreground: 'fabd2f' },
    { token: 'function', foreground: '83a598' },
    { token: 'function.call', foreground: '83a598' },
    { token: 'method', foreground: '83a598' },
    { token: 'method.call', foreground: '83a598' },
    { token: 'variable', foreground: 'ebdbb2' },
    { token: 'variable.name', foreground: 'ebdbb2' },
    { token: 'variable.parameter', foreground: 'd5c4a1' },
    { token: 'variable.language', foreground: 'fe8019' },
    { token: 'constant', foreground: 'd3869b' },
    { token: 'constant.language', foreground: 'fe8019' },
    { token: 'constant.numeric', foreground: 'd3869b' },
    { token: 'tag', foreground: '83a598' },
    { token: 'tag.id', foreground: '83a598' },
    { token: 'tag.class', foreground: '8ec07c' },
    { token: 'metatag', foreground: 'd3869b' },
    { token: 'attribute.name', foreground: 'fabd2f' },
    { token: 'attribute.value', foreground: 'b8bb26' },
    { token: 'delimiter', foreground: 'a89984' },
    { token: 'delimiter.bracket', foreground: '83a598' },
    { token: 'delimiter.curly', foreground: 'd3869b' },
    { token: 'delimiter.parenthesis', foreground: 'a89984' },
    { token: 'operator', foreground: 'fe8019' },
    { token: 'operator.assignment', foreground: 'fe8019' },
    { token: 'identifier', foreground: 'ebdbb2' },
    { token: 'namespace', foreground: '83a598' },
    { token: 'decorator', foreground: 'fe8019' },
    { token: 'annotation', foreground: 'fe8019' },
    { token: 'regexp', foreground: 'b8bb26' },
    { token: 'invalid', foreground: 'fb4934', fontStyle: 'underline' },
  ],
  colors: {
    'editor.background': '#1d2021',
    'editor.foreground': '#ebdbb2',
    'editor.lineHighlightBackground': '#3c383680',
    'editor.selectionBackground': '#504945',
    'editor.inactiveSelectionBackground': '#3c383680',
    'editorLineNumber.foreground': '#7c6f64',
    'editorLineNumber.activeForeground': '#d5c4a1',
    'editorCursor.foreground': '#fabd2f',
    'editorIndentGuide.background': '#50494580',
    'editorIndentGuide.activeBackground': '#665c54',
    'editor.selectionHighlightBackground': '#fabd2f22',
    'editorBracketMatch.background': '#fabd2f18',
    'editorBracketMatch.border': '#fabd2f55',
    'editorGutter.background': '#1d2021',
    'diffEditor.insertedTextBackground': '#b8bb2622',
    'diffEditor.removedTextBackground': '#fb493422',
    'minimap.background': '#1d2021',
    'minimapGutter.background': '#1d2021',
    'minimapSlider.background': '#50494566',
    'minimapSlider.hoverBackground': '#665c5488',
    'minimapSlider.activeBackground': '#7c6f64aa',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#50494566',
    'scrollbarSlider.hoverBackground': '#665c5488',
    'scrollbarSlider.activeBackground': '#7c6f64aa',
  },
}
